version: '3.8'
services:
  kanga2:
    build: .
    ports:
      - "5000:5000"
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/snd:/dev/snd" # For audio output, optional
    environment:
      - FLASK_APP=app/main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./playlist.json:/app/playlist.json
    restart: unless-stopped
    privileged: true # Needed for framebuffer access
